name: hitl_banana

task_name: banana

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    wrist_rgb:
      shape: [84, 84, 3]
      type: rgb
    back_rgb:
      shape: [84, 84, 3]
      type: rgb
    agent_pos:
      shape: [11] # size of the robot state array (7 for joint pos and 1 for gripper position and 3 for ee_position)
      type: low_dimx
  action:
    shape: [3] # size of the action array (4 for ee_orientation in qx, qy, qz, qw)

env_runner: null # Null because we dont need any simulation environments since were in the real world

dataset:
  _target_: diffusion_policy_3d.dataset.hitl_dataset.HitlDataset
  zarr_path: data/hitl_banana.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.02
  max_train_episodes: 90
