name: hitl_unstack

task_name: unstack

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    point_cloud:
      shape: [1024, 3]
      type: point_cloud
    agent_pos:
      shape: [11] # 16 for projected unit norm diffs
      type: low_dimx
  action:
    shape: [3]

env_runner: null # Null because we dont need any simulation environments since were in the real world

dataset:
  _target_: diffusion_policy_3d.dataset.hitl_dataset.HitlDataset
  zarr_path: data/hitl_unstack.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.02
  max_train_episodes: 90
  model_type: "hitl_hgd"
