name: hitl_unstack

task_name: unstack

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    point_cloud:
      # shape: [1024, 3] # colorless pointcloud
      # shape: [1024, 4] # colored pointcloud
      shape: [2048, 6] # double size colored pointcloud
      type: point_cloud
    agent_pos:
      # shape: [12] # size of the robot state array (7 for joint pos and 1 for gripper position and 3 for ee_position and 1 for stage)
      # shape: [11] # size of the robot state array (7 for joint pos and 3 for ee_position and 1 for stage)
      # shape: [7] # size of the robot state array (3 for ee_position and 1 for stage and 3 for ee_pos - centroid)
      shape: [4] # size of the robot state array (3 for ee_position and 1 for stage)
      # shape: [3] # size of the robot state array (3 for ee_position)
      type: low_dimx
  action:
    # shape: [4] # size of the action array (4 for ee_orientation in qx, qy, qz, qw)
    shape: [3] # size of the action array (4 for ee_orientation in yaw pitch roll)

env_runner: null # Null because we dont need any simulation environments since were in the real world

dataset:
  _target_: diffusion_policy_3d.dataset.hitl_dataset.HitlDataset
  zarr_path: data/hitl_unstack.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.02
  max_train_episodes: 90
