name: hitl_plate_xbox

task_name: plate_xbox

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    back_point_cloud:
      shape: [1024, 3]
      type: point_cloud
    agent_pos:
      shape: [3] # size of the robot state array (1 for gripper position and 3 for ee_position)
      type: low_dimx
  action:
    shape: [3] # size of the action array (3 for ee_orientation in rotvec)

env_runner: null # Null because we dont need any simulation environments since were in the real world

dataset:
  _target_: diffusion_policy_3d.dataset.hitl_dataset.HitlDataset
  zarr_path: data/hitl_plate_xbox.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.02
  max_train_episodes: 90
